spring:
  datasource:
    master:
      password: xzst
      url: jdbc:oracle:thin:@53.80.6.37:1521:orcl
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: xzst
      type: com.zaxxer.hikari.HikariDataSource
    cluster:
    - key: ajfl
      password: qprmsEFhnFKVRM9f
      url: jdbc:oracle:thin:@10.125.129.66:1521:xtba
      idle-timeout: 20000
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: xtba_qbpt
      type: com.zaxxer.hikari.HikariDataSource
    - key: slave2
      password: 198412
      url: jdbc:mysql://localhost:3306/lht_test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
      idle-timeout: 20000
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      type: com.zaxxer.hikari.HikariDataSource
  kafka:
    consumer:
      bootstrap-servers: 53.80.6.45:9092,53.80.6.46:9092,53.80.6.47:9092,53.80.6.48:9092
      enable-auto-commit: true
      auto-offset-reset: latest
      group-id: modi_g_1
    producer:
      bootstrap-servers: 53.80.6.45:9092,53.80.6.46:9092,53.80.6.47:9092,53.80.6.48:9092
      topic: modi
      acks: all
      retries: 0
      batch-size: 4096
      buffer-memory: 40960
      linger: 1
      client-id: socketClient

#server:
#  tomcat:
##  max-http-header-size: 655360
#  port: 9090

mybatis:
    mapper-locations: classpath:mapper/*.xml
    config-location: classpath:mapper/mybatisConfig/mybatisConfig.xml

JWT:
  header: Authorization
  secret: MasterSecret
  expiration: 10080
  tokenHead: "Bearer "


#httpclient配置参数
#最大连接数
http:
  maxTotal: 100
  #并发数
  defaultMaxPerRoute: 20
  #创建连接的最长时间
  connectTimeout: 10000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 5000
  #数据传输的最长时间
  socketTimeout: 100000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true


shumo:
  token: "Basic bWFzdGVyOm1vZGVsX21hc3Rlcg=="
  #获取模型列表
  modelListUrl: "http://53.80.6.36:7047/task/searchAll"
  #获取模型下所有的结果集
  resultSetList: "http://53.80.6.36:7047/task/list"
  #获取结果集的列信息
  resultSetColInfoUrl: "http://53.80.6.36:7047/task/result/columns?resultId="

frontend-config:
  toShuMiaoUrl: "http://53.80.6.46:8060"





